supply_chain_hub:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID', 'smart-supply-and-inventory') }}"
      dataset: "{{ env_var('GCP_DATASET_DEV', 'sc_dev') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_KEYFILE_PATH', 'credentials/sa_dbt.json') }}"
      location: US
      priority: interactive
      timeout_seconds: 300
      retries: 1

    local:
      type: duckdb
      path: "../data/warehouse.duckdb"
      threads: 4
      extensions:
        - parquet

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID', 'smart-supply-and-inventory') }}"
      dataset: "{{ env_var('GCP_DATASET_PROD', 'analytics_supply_chain') }}"
      threads: 8
      keyfile: "{{ env_var('GCP_KEYFILE_PATH', 'credentials/sa_dbt.json') }}"
      location: US
      priority: interactive
      timeout_seconds: 600
      retries: 1
